import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';

// this functions is also mentioned my api page and explained how the would use.
// in this pages we practice them.

async function fetchUserAPI(){
  let response = await fetch("/api/users/");
  let data = await response.json();

  return data
}

async function getOneData(param){
  let response = await fetch(`/api/users/${param}`);
  let data = await response.json();

  return data;
}

async function postNewUser(param){
  let response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(param)});
  let data = await response.json();

  return data;
}

async function putTheUser(dynamicRoute, propertyAndValueObject){
  let response = await fetch(`/api/users/${dynamicRoute}`, { method: "PUT", headers: { "Content-Type": "application/json"}, body: JSON.stringify(propertyAndValueObject)});
  let data = await response.json();

  return data;
}

async function deleteTheUser(dynamicRoute){
  let response = await fetch(`/api/users/${dynamicRoute}`, { method: "DELETE" });
  let data = await response.json();

  return data;
}

export default function Home() {
  let [data, setData] = useState(null);
  let [username, setUsername] = useState("");
  let [password, setPassword] = useState("");
  let [email, setEmail] = useState("");
  let [telephone, setTelephone] = useState("");
  let router = useRouter();
  let [individualData, setIndividualData] = useState(null);

  class user{
    constructor(){
      this.username = username;
      this.password = password;
      this.email = email;
      this.telephone = telephone;
      this.id = Math.random()*1000000;
    }
  }

  console.log(router.basePath)

  useEffect(function(){
    fetchUserAPI().then(param => setData(param))
    getOneData("user4").then(param => setIndividualData(param));
  }, []);

  //console.log(individualData.exactUser);

  function handleSubmit(parameter){
    parameter.preventDefault();

    let userObject = new user()/*{ username, password, email, telephone }*/

    postNewUser(userObject).then(data => console.log(data));
  }

  async function fetchTheUsersList(){
    return fetchUserAPI().then(param => setData(param))
  }

  async function putTheIndividualUser(){
    await putTheUser("user4", { email: "user4changed@gmail.com" }).then(param => console.log(param));
  }

  async function deleteTheIndividualUser(){
    await deleteTheUser("user11").then(param => console.log(param));
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Register To Our Website!</h2>

      <div className={styles.formContainer}>
        <form onSubmit={handleSubmit}>
          <label>
            <span>username:</span>
            <input type="text" onChange={(param) => setUsername(param.target.value)} value={username} required/>
          </label>

          <label>
            <span>password:</span>
            <input type="password" onChange={(param) => setPassword(param.target.value)} value={password} required/>
          </label>

          <label>
            <span>email:</span>
            <input type="email" onChange={(param) => setEmail(param.target.value)} value={email} required/>
          </label>  

          <label>
            <span>telephone:</span>
            <input type="tel" onChange={(param) => setTelephone(param.target.value)} value={telephone} required/>
          </label>  

          <input type="submit" value="register" />
        </form> 
      </div>

      <button onClick={fetchTheUsersList}>Click to fetch users list</button>

      {data && data.userData.map(function(param){
          return ( <ul key={param.id}>
            <li>{param.username}</li>
          </ul>
        )})}

      {<button onClick={putTheIndividualUser}>Click to button for put user4's email</button>}

      {<button onClick={deleteTheIndividualUser}>Delete User 11</button>}


    </div>
  )
}
